package com.example.toolsonrent.ui.toollistscreen

import android.net.Uri
import android.view.LayoutInflater
import android.view.ViewGroup
import androidx.core.content.ContextCompat
import androidx.recyclerview.widget.DiffUtil
import androidx.recyclerview.widget.ListAdapter
import androidx.recyclerview.widget.RecyclerView
import com.example.toolsonrent.R // Auto-resolved by Android Studio/build system
import com.example.toolsonrent.database.entity.Tool
import com.example.toolsonrent.databinding.ItemToolBinding // Auto-generated by ViewBinding

class ToolListAdapter : ListAdapter<Tool, ToolListAdapter.ToolViewHolder>(ToolDiffCallback) {

    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): ToolViewHolder {
        val binding = ItemToolBinding.inflate(LayoutInflater.from(parent.context), parent, false)
        return ToolViewHolder(binding)
    }

    override fun onBindViewHolder(holder: ToolViewHolder, position: Int) {
        val tool = getItem(position)
        holder.bind(tool)
    }

    inner class ToolViewHolder(private val binding: ItemToolBinding) : RecyclerView.ViewHolder(binding.root) {
        fun bind(tool: Tool) {
            binding.textViewToolNameItem.text = tool.name
            // Consider using NumberFormat.getCurrencyInstance(locale) for proper currency formatting
            binding.textViewRentalPriceItem.text = String.format(itemView.context.resources.configuration.locales.get(0), "%.2f / day", tool.rentalPrice)


            if (tool.isAvailable) {
                binding.textViewAvailabilityItem.text = itemView.context.getString(R.string.text_available)
                binding.textViewAvailabilityItem.setTextColor(ContextCompat.getColor(itemView.context, R.color.status_available_green))
            } else {
                binding.textViewAvailabilityItem.text = itemView.context.getString(R.string.text_rented)
                binding.textViewAvailabilityItem.setTextColor(ContextCompat.getColor(itemView.context, R.color.status_rented_red))
            }

            // Placeholder for image loading
            if (tool.imageUri != null) {
                // In a real app, you would use Glide or Picasso here:
                // Glide.with(itemView.context).load(Uri.parse(tool.imageUri)).placeholder(R.drawable.ic_menu_gallery).into(binding.imageViewToolItem)
                // For now, just a different placeholder to indicate a URI is present
                binding.imageViewToolItem.setImageResource(R.drawable.ic_launcher_background) // Example placeholder
            } else {
                binding.imageViewToolItem.setImageResource(android.R.drawable.ic_menu_gallery) // Default placeholder
            }

            // Example of setting an onClickListener for the item if needed
            // itemView.setOnClickListener {
            //     onItemClickListener?.invoke(tool)
            // }
        }
    }

    // Optional: Listener for item clicks
    // var onItemClickListener: ((Tool) -> Unit)? = null

    companion object ToolDiffCallback : DiffUtil.ItemCallback<Tool>() {
        override fun areItemsTheSame(oldItem: Tool, newItem: Tool): Boolean {
            return oldItem.id == newItem.id
        }

        override fun areContentsTheSame(oldItem: Tool, newItem: Tool): Boolean {
            // This assumes Tool is a data class, so `==` checks for content equality.
            // If Tool was not a data class, you'd need to compare fields manually.
            return oldItem == newItem
        }
    }
}
