package com.example.toolsonrent.ui.toollistscreen

import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.fragment.app.Fragment
import androidx.lifecycle.Lifecycle
import androidx.lifecycle.ViewModelProvider
import androidx.lifecycle.lifecycleScope
import androidx.lifecycle.repeatOnLifecycle
import androidx.navigation.fragment.findNavController
import androidx.recyclerview.widget.LinearLayoutManager
import androidx.recyclerview.widget.DividerItemDecoration // Uncomment if you want dividers
import com.example.toolsonrent.R
import com.example.toolsonrent.databinding.FragmentToolListBinding // Auto-generated by ViewBinding
import kotlinx.coroutines.launch

class ToolListFragment : Fragment() {

    private var _binding: FragmentToolListBinding? = null
    private val binding get() = _binding!!

    private lateinit var viewModel: ToolListViewModel
    private lateinit var toolListAdapter: ToolListAdapter

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {
        _binding = FragmentToolListBinding.inflate(inflater, container, false)
        return binding.root
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        // Initialize ViewModel using the fragment as the ViewModelStoreOwner
        viewModel = ViewModelProvider(this)[ToolListViewModel::class.java]
        toolListAdapter = ToolListAdapter() // Assuming default constructor or one that doesn't need params here

        setupRecyclerView()
        observeTools()
        setupFab()
    }

    private fun setupRecyclerView() {
        binding.recyclerViewTools.apply {
            adapter = toolListAdapter
            layoutManager = LinearLayoutManager(requireContext())
            // Optional: Add item decoration for visual separation. Uncomment to use.
            // addItemDecoration(DividerItemDecoration(requireContext(), LinearLayoutManager.VERTICAL))
        }
    }

    private fun observeTools() {
        // Use viewLifecycleOwner for launching coroutines that observe LiveData or Flows
        viewLifecycleOwner.lifecycleScope.launch {
            // repeatOnLifecycle ensures that the collection starts when the Fragment is STARTED
            // and stops when it is STOPPED, preventing resource leaks.
            repeatOnLifecycle(Lifecycle.State.STARTED) {
                viewModel.allTools.collect { toolsList ->
                    toolListAdapter.submitList(toolsList)
                }
            }
        }
    }

    private fun setupFab() {
        binding.fabAddTool.setOnClickListener {
            // This ID needs to be defined in your navigation graph (e.g., res/navigation/nav_graph.xml)
            // as an action from ToolListFragment to AddToolFragment.
            try {
                findNavController().navigate(R.id.action_toolListFragment_to_addToolFragment)
            } catch (e: IllegalArgumentException) {
                // This can happen if the ID is not found in the current destination's actions.
                // Log this or show a toast for debugging during development.
                // For example: Toast.makeText(requireContext(), "Navigation action not found. Check nav_graph.xml", Toast.LENGTH_LONG).show()
                // Log.e("ToolListFragment", "Navigation action R.id.action_toolListFragment_to_addToolFragment not found", e)
            }
        }
    }

    override fun onDestroyView() {
        super.onDestroyView()
        _binding = null // Crucial to avoid memory leaks with ViewBinding
    }
}
