package com.example.toolsonrent.ui.addtool

import android.app.Application
import android.util.Log
import androidx.lifecycle.*
import com.example.toolsonrent.database.AppDatabase
import com.example.toolsonrent.database.entity.Tool
import kotlinx.coroutines.launch

class AddToolViewModel(application: Application) : AndroidViewModel(application) {

    private val toolDao = AppDatabase.getInstance(application).toolDao()

    private val _saveResult = MutableLiveData<Result<Unit>>()
    val saveResult: LiveData<Result<Unit>> = _saveResult

    fun addTool(
        name: String,
        description: String?,
        priceStr: String,
        totalQuantityStr: String, // New parameter, replaced isAvailable
        imageUri: String?
    ) {
        val price = priceStr.toDoubleOrNull()
        val totalQuantity = totalQuantityStr.toIntOrNull() // Parse total quantity

        // Validations
        if (name.isBlank()) {
            _saveResult.postValue(Result.failure(IllegalArgumentException("Tool name cannot be empty.")))
            return
        }
        if (price == null || price <= 0) {
            _saveResult.postValue(Result.failure(IllegalArgumentException("Enter a valid positive rental price.")))
            return
        }
        if (totalQuantity == null || totalQuantity <= 0) {
            _saveResult.postValue(Result.failure(IllegalArgumentException("Total quantity must be a positive number.")))
            return
        }

        // Create the Tool object with new quantity fields
        val newTool = Tool(
            id = 0, // id is auto-generated by Room
            name = name,
            description = description?.ifBlank { null },
            rentalPrice = price,
            totalQuantity = totalQuantity, // Use parsed quantity
            currentAvailableQuantity = totalQuantity, // Initialize available quantity to total quantity
            imageUri = imageUri
        )

        viewModelScope.launch {
            try {
                toolDao.insert(newTool)
                _saveResult.postValue(Result.success(Unit))
            } catch (e: Exception) {
                Log.e("AddToolViewModel", "Error inserting new tool into database", e)
                _saveResult.postValue(Result.failure(e))
            }
        }
    }
}
