package com.example.toolsonrent.ui.addtool

import android.app.Application
import android.util.Log
import androidx.lifecycle.*
import com.example.toolsonrent.database.AppDatabase
import com.example.toolsonrent.database.entity.Tool
import kotlinx.coroutines.launch

class AddToolViewModel(application: Application) : AndroidViewModel(application) {

    private val toolDao = AppDatabase.getInstance(application).toolDao()

    // Save result now returns the ID of the newly created Tool (template)
    private val _saveResult = MutableLiveData<Result<Long>>()
    val saveResult: LiveData<Result<Long>> = _saveResult

    fun addToolType( // Renamed for clarity, as it now adds a tool type/template
        name: String,
        description: String?,
        priceStr: String,
        imageUri: String?
    ) {
        val price = priceStr.toDoubleOrNull()

        // Validations
        if (name.isBlank()) {
            _saveResult.postValue(Result.failure(IllegalArgumentException("Tool name cannot be empty.")))
            return
        }
        if (price == null || price <= 0) {
            _saveResult.postValue(Result.failure(IllegalArgumentException("Enter a valid positive rental price.")))
            return
        }
        // Quantity validation removed

        // Create the Tool object (template)
        val newToolType = Tool(
            id = 0, // id is auto-generated by Room
            name = name,
            description = description?.ifBlank { null },
            rentalPrice = price,
            // totalQuantity and currentAvailableQuantity removed
            imageUri = imageUri
        )

        viewModelScope.launch {
            try {
                // Assuming ToolDao.insert is updated or already returns the new row ID (Long)
                val newToolId = toolDao.insert(newToolType)
                if (newToolId > 0) { // Check if insert was successful (ID > 0)
                    _saveResult.postValue(Result.success(newToolId))
                } else {
                    _saveResult.postValue(Result.failure(Exception("Failed to save tool type, invalid ID returned.")))
                }
            } catch (e: Exception) {
                Log.e("AddToolViewModel", "Error inserting new tool type into database", e)
                _saveResult.postValue(Result.failure(e))
            }
        }
    }
}
