package com.example.toolsonrent.ui.addtool

import android.app.Application
import android.util.Log // For logging if needed
import androidx.lifecycle.*
import com.example.toolsonrent.database.AppDatabase
import com.example.toolsonrent.database.entity.Tool
import kotlinx.coroutines.launch

class AddToolViewModel(application: Application) : AndroidViewModel(application) {

    private val toolDao = AppDatabase.getInstance(application).toolDao()

    private val _saveResult = MutableLiveData<Result<Unit>>()
    val saveResult: LiveData<Result<Unit>> = _saveResult

    // Changed from saveTool(tool: Tool) to explicitly take parameters
    fun addTool(
        name: String,
        description: String?,
        priceStr: String,
        isAvailable: Boolean,
        imageUri: String? // New parameter
    ) {
        val price = priceStr.toDoubleOrNull()
        if (name.isBlank()) {
            _saveResult.postValue(Result.failure(IllegalArgumentException("Tool name cannot be empty.")))
            return
        }
        if (price == null || price <= 0) {
            _saveResult.postValue(Result.failure(IllegalArgumentException("Enter a valid positive rental price.")))
            return
        }

        // Create the Tool object within the ViewModel
        val newTool = Tool(
            id = 0, // id is auto-generated by Room, so 0 is appropriate for a new entity
            name = name,
            description = description?.ifBlank { null }, // Store null if description is blank
            rentalPrice = price,
            isAvailable = isAvailable,
            imageUri = imageUri // Use the passed imageUri
        )

        viewModelScope.launch {
            try {
                toolDao.insert(newTool)
                _saveResult.postValue(Result.success(Unit))
            } catch (e: Exception) {
                Log.e("AddToolViewModel", "Error inserting new tool into database", e)
                _saveResult.postValue(Result.failure(e))
            }
        }
    }
}
