package com.example.toolsonrent.ui.dashboard

import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.util.Log
import android.widget.Toast
import androidx.fragment.app.Fragment
import androidx.lifecycle.Lifecycle
import androidx.lifecycle.ViewModelProvider
import androidx.lifecycle.lifecycleScope
import androidx.lifecycle.repeatOnLifecycle
import androidx.navigation.fragment.findNavController
import com.example.toolsonrent.R
import kotlinx.coroutines.launch
import com.example.toolsonrent.databinding.FragmentDashboardBinding // Will be generated by ViewBinding

class DashboardFragment : Fragment() {

    private var _binding: FragmentDashboardBinding? = null
    // This property is only valid between onCreateView and onDestroyView.
    private val binding get() = _binding!!

    private lateinit var viewModel: DashboardViewModel

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {
        _binding = FragmentDashboardBinding.inflate(inflater, container, false)
        return binding.root
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        viewModel = ViewModelProvider(this)[DashboardViewModel::class.java]

        binding.buttonGoToToolList.setOnClickListener {
            try {
                findNavController().navigate(R.id.action_dashboardFragment_to_toolListFragment)
            } catch (e: IllegalArgumentException) {
                // This can happen if the NavController is not yet fully set up or action is missing
                // Log error or show a Toast for debugging during development
                Log.e("DashboardFragment", "Navigation action_dashboardFragment_to_toolListFragment not found or NavController issue.", e)
                Toast.makeText(context, "Error: Could not navigate. Action not found.", Toast.LENGTH_SHORT).show()
            }
        }

        binding.buttonManageCustomersDashboard.setOnClickListener {
            try {
                findNavController().navigate(R.id.action_dashboardFragment_to_customerListFragment)
            } catch (e: IllegalArgumentException) {
                Log.e("DashboardFragment", "Navigation action_dashboardFragment_to_customerListFragment not found.", e)
                Toast.makeText(context, "Error: Manage Customers action not found.", Toast.LENGTH_SHORT).show()
            }
        }

        binding.buttonManageReturnsDashboard.setOnClickListener {
            try {
                findNavController().navigate(R.id.action_dashboardFragment_to_activeRentalsFragment)
            } catch (e: IllegalArgumentException) {
                Log.e("DashboardFragment", "Navigation action_dashboardFragment_to_activeRentalsFragment not found.", e)
                Toast.makeText(context, "Error: Manage Returns action not found.", Toast.LENGTH_SHORT).show()
            }
        }

        binding.buttonViewOverdueReportDashboard.setOnClickListener {
            try {
                findNavController().navigate(R.id.action_dashboardFragment_to_overdueRentalsReportFragment)
            } catch (e: IllegalArgumentException) {
                Log.e("DashboardFragment", "Navigation action_dashboardFragment_to_overdueRentalsReportFragment not found.", e)
                Toast.makeText(context, "Error: Overdue Report action not found.", Toast.LENGTH_SHORT).show()
            }
        }

        binding.buttonCustomerHistoryReportDashboard.setOnClickListener {
            try {
                findNavController().navigate(R.id.action_dashboardFragment_to_selectCustomerForReportFragment)
            } catch (e: IllegalArgumentException) {
                Log.e("DashboardFragment", "Navigation action_dashboardFragment_to_selectCustomerForReportFragment not found.", e)
                Toast.makeText(context, "Error: Customer History Report action not found.", Toast.LENGTH_SHORT).show()
            }
        }

        binding.buttonToolHistoryReportDashboard.setOnClickListener {
            try {
                findNavController().navigate(R.id.action_dashboardFragment_to_selectToolForReportFragment)
            } catch (e: IllegalArgumentException) {
                Log.e("DashboardFragment", "Navigation action_dashboardFragment_to_selectToolForReportFragment not found.", e)
                Toast.makeText(context, "Error: Tool History Report action not found.", Toast.LENGTH_SHORT).show()
            }
        }

        binding.buttonInventoryReportDashboard.setOnClickListener {
            try {
                findNavController().navigate(R.id.action_dashboardFragment_to_inventoryReportFragment)
            } catch (e: IllegalArgumentException) {
                Log.e("DashboardFragment", "Navigation action_dashboardFragment_to_inventoryReportFragment not found.", e)
                Toast.makeText(context, "Error: Inventory Report action not found.", Toast.LENGTH_SHORT).show()
            }
        }

        binding.buttonProfitLossReportDashboard.setOnClickListener {
            try {
                findNavController().navigate(R.id.action_dashboardFragment_to_profitLossReportFragment)
            } catch (e: IllegalArgumentException) {
                Log.e("DashboardFragment", "Navigation action_dashboardFragment_to_profitLossReportFragment not found.", e)
                Toast.makeText(context, "Error: Profit & Loss Report action not found.", Toast.LENGTH_SHORT).show()
            }
        }

        observeMetricCounts() // Call the new method

        binding.buttonAddNewToolDashboard.setOnClickListener {
            try {
                // Assuming action_dashboardFragment_to_addToolFragment will be created in nav_graph
                findNavController().navigate(R.id.action_dashboardFragment_to_addToolFragment)
            } catch (e: IllegalArgumentException) {
                Log.e("DashboardFragment", "Navigation action_dashboardFragment_to_addToolFragment not found.", e)
                Toast.makeText(context, "Error: Add Tool action not found.", Toast.LENGTH_SHORT).show()
            }
        }

        binding.buttonAddNewCustomerDashboard.setOnClickListener {
            Toast.makeText(requireContext(), "Add New Customer: Coming soon!", Toast.LENGTH_SHORT).show()
        }

        binding.buttonStartNewRentalDashboard.setOnClickListener {
            try {
                findNavController().navigate(R.id.action_dashboardFragment_to_startRentalFragment)
            } catch (e: IllegalArgumentException) {
                Log.e("DashboardFragment", "Navigation action_dashboardFragment_to_startRentalFragment not found.", e)
                Toast.makeText(context, "Error: Start Rental action not found.", Toast.LENGTH_SHORT).show()
            }
        }

        // Setup for MaterialCalendarView
        binding.materialCalendarDashboard.setOnDateChangedListener { widget, date, selected ->
            // 'date' is a CalendarDay object from the library
            // CalendarDay.getMonth() is 0-indexed (0-11), so add 1 for human-readable month.
            val displayMonth = date.month + 1
            val displayText = "Selected date: ${date.day}/$displayMonth/${date.year}"
            Toast.makeText(requireContext(), displayText, Toast.LENGTH_SHORT).show()

            // TODO: Fetch and display tools due on this date or other relevant info
            // This might involve calling a method on the ViewModel:
            // viewModel.fetchRentalsDueOn(date)
        }
    }

    private fun observeMetricCounts() {
        viewLifecycleOwner.lifecycleScope.launch {
            repeatOnLifecycle(Lifecycle.State.STARTED) {
                // Observe Available Tools Count
                launch {
                    viewModel.availableToolsCount.collect { count ->
                        binding.textViewAvailableCountValue.text = count.toString()
                    }
                }

                // Observe Rented Tools Count
                launch {
                    viewModel.rentedToolsCount.collect { count ->
                        binding.textViewRentedCountValue.text = count.toString()
                    }
                }

                // Placeholder for Overdue Tools Count - it will show tools:text or be blank
                // To explicitly set a placeholder if the value isn't ready from ViewModel:
                // binding.textViewOverdueCountValue.text = "-"
            }
        }
    }

    override fun onDestroyView() {
        super.onDestroyView()
        _binding = null // Important for preventing memory leaks
    }
}
