package com.example.toolsonrent.ui.dashboard

import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.util.Log
import android.widget.Toast
import androidx.fragment.app.Fragment
import androidx.lifecycle.ViewModelProvider
import androidx.navigation.fragment.findNavController
import com.example.toolsonrent.R
import com.example.toolsonrent.databinding.FragmentDashboardBinding // Will be generated by ViewBinding

class DashboardFragment : Fragment() {

    private var _binding: FragmentDashboardBinding? = null
    // This property is only valid between onCreateView and onDestroyView.
    private val binding get() = _binding!!

    private lateinit var viewModel: DashboardViewModel

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {
        _binding = FragmentDashboardBinding.inflate(inflater, container, false)
        return binding.root
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        viewModel = ViewModelProvider(this)[DashboardViewModel::class.java]

        binding.buttonGoToToolList.setOnClickListener {
            try {
                findNavController().navigate(R.id.action_dashboardFragment_to_toolListFragment)
            } catch (e: IllegalArgumentException) {
                // This can happen if the NavController is not yet fully set up or action is missing
                // Log error or show a Toast for debugging during development
                Log.e("DashboardFragment", "Navigation action_dashboardFragment_to_toolListFragment not found or NavController issue.", e)
                Toast.makeText(context, "Error: Could not navigate. Action not found.", Toast.LENGTH_SHORT).show()
            }
        }
    }

    override fun onDestroyView() {
        super.onDestroyView()
        _binding = null // Important for preventing memory leaks
    }
}
