package com.example.toolsonrent.ui.dashboard

import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.util.Log
import android.widget.Toast
import androidx.fragment.app.Fragment
import androidx.lifecycle.Lifecycle
import androidx.lifecycle.ViewModelProvider
import androidx.lifecycle.lifecycleScope
import androidx.lifecycle.repeatOnLifecycle
import androidx.navigation.fragment.findNavController
import com.example.toolsonrent.R
import kotlinx.coroutines.launch
import com.example.toolsonrent.databinding.FragmentDashboardBinding // Will be generated by ViewBinding
import kotlinx.coroutines.flow.collectLatest // For collecting StateFlows
import java.text.NumberFormat // For currency formatting
import java.util.Locale // For Locale.getDefault()

class DashboardFragment : Fragment() {

    private var _binding: FragmentDashboardBinding? = null
    private val binding get() = _binding!!

    private lateinit var viewModel: DashboardViewModel

    // Currency formatter for displaying profit values
    private val currencyFormat: NumberFormat = NumberFormat.getCurrencyInstance(Locale.getDefault()).apply {
        maximumFractionDigits = 2 // Ensure two decimal places for currency
    }


    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {
        _binding = FragmentDashboardBinding.inflate(inflater, container, false)
        // ViewModel is initialized in onViewCreated for consistency and access to `this` (Fragment)
        return binding.root
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        viewModel = ViewModelProvider(this)[DashboardViewModel::class.java]

        // Setup Button Click Listeners
        setupNavigationButtonListeners()

        observeDashboardMetrics() // Updated method name and content

        // Setup for MaterialCalendarView (existing)
        binding.materialCalendarDashboard.setOnDateChangedListener { widget, date, selected ->
            val displayMonth = date.month + 1
            val displayText = "Selected date: ${date.day}/$displayMonth/${date.year}"
            Toast.makeText(requireContext(), displayText, Toast.LENGTH_SHORT).show()
            // TODO: viewModel.fetchRentalsDueOn(date)
        }
    }

    private fun setupNavigationButtonListeners() {
        binding.buttonGoToToolList.setOnClickListener {
            try { findNavController().navigate(R.id.action_dashboardFragment_to_toolListFragment) }
            catch (e: IllegalArgumentException) { handleNavError("Manage Tools", e) }
        }
        binding.buttonManageCustomersDashboard.setOnClickListener {
            try { findNavController().navigate(R.id.action_dashboardFragment_to_customerListFragment) }
            catch (e: IllegalArgumentException) { handleNavError("Manage Customers", e) }
        }
        binding.buttonManageReturnsDashboard.setOnClickListener {
            try { findNavController().navigate(R.id.action_dashboardFragment_to_activeRentalsFragment) }
            catch (e: IllegalArgumentException) { handleNavError("Manage Returns", e) }
        }
        binding.buttonViewOverdueReportDashboard.setOnClickListener {
            try { findNavController().navigate(R.id.action_dashboardFragment_to_overdueRentalsReportFragment) }
            catch (e: IllegalArgumentException) { handleNavError("Overdue Report", e) }
        }
        binding.buttonCustomerHistoryReportDashboard.setOnClickListener {
            try { findNavController().navigate(R.id.action_dashboardFragment_to_selectCustomerForReportFragment) }
            catch (e: IllegalArgumentException) { handleNavError("Customer History Report", e) }
        }
        binding.buttonToolHistoryReportDashboard.setOnClickListener {
            try { findNavController().navigate(R.id.action_dashboardFragment_to_selectToolForReportFragment) }
            catch (e: IllegalArgumentException) { handleNavError("Tool History Report", e) }
        }
        binding.buttonInventoryReportDashboard.setOnClickListener {
            try { findNavController().navigate(R.id.action_dashboardFragment_to_inventoryReportFragment) }
            catch (e: IllegalArgumentException) { handleNavError("Inventory Report", e) }
        }
        binding.buttonProfitLossReportDashboard.setOnClickListener {
            try { findNavController().navigate(R.id.action_dashboardFragment_to_profitLossReportFragment) }
            catch (e: IllegalArgumentException) { handleNavError("Profit & Loss Report", e) }
        }
        binding.buttonAddNewToolDashboard.setOnClickListener {
            try { findNavController().navigate(R.id.action_dashboardFragment_to_addToolFragment) }
            catch (e: IllegalArgumentException) { handleNavError("Add New Tool", e) }
        }
        binding.buttonAddNewCustomerDashboard.setOnClickListener {
            Toast.makeText(requireContext(), "Add New Customer: Coming soon!", Toast.LENGTH_SHORT).show()
        }
        binding.buttonStartNewRentalDashboard.setOnClickListener {
            try { findNavController().navigate(R.id.action_dashboardFragment_to_startRentalFragment) }
            catch (e: IllegalArgumentException) { handleNavError("Start New Rental", e) }
        }
    }

    private fun handleNavError(actionName: String, exception: IllegalArgumentException) {
        Log.e("DashboardFragment", "Navigation for '$actionName' failed. Action not found.", exception)
        Toast.makeText(context, "Error: $actionName action not found.", Toast.LENGTH_SHORT).show()
    }

    private fun observeDashboardMetrics() { // Renamed from observeMetricCounts
        viewLifecycleOwner.lifecycleScope.launch {
            repeatOnLifecycle(Lifecycle.State.STARTED) {
                // Observe Available Tools Count
                launch {
                    viewModel.availableToolsCount.collectLatest { count ->
                        binding.textViewAvailableCountValue.text = count.toString()
                    }
                }

                // Observe Rented Tools Count
                launch {
                    viewModel.rentedToolsCount.collectLatest { count ->
                        binding.textViewRentedCountValue.text = count.toString()
                    }
                }

                // Observe Overdue Tools Count
                launch {
                    viewModel.overdueToolsCount.collectLatest { count ->
                        binding.textViewOverdueCountValue.text = count.toString()
                    }
                }

                // Observe Daily Profit
                launch {
                    viewModel.dailyProfit.collectLatest { profit ->
                        binding.textViewDailyProfitValue.text = currencyFormat.format(profit)
                    }
                }

                // Observe Monthly Profit
                launch {
                    viewModel.monthlyProfit.collectLatest { profit ->
                        binding.textViewMonthlyProfitValue.text = currencyFormat.format(profit)
                    }
                }
            }
        }
    }

    override fun onDestroyView() {
        super.onDestroyView()
        _binding = null // Important for preventing memory leaks
    }
}
